const ALMOST_BLACK = "#1B1B1B";
const DARK_GREY_1 = "#2B2A2F";
const DARK_GREY_2 = "#232323";
const BLUE_GREEN = "#147A6D";
const LIPSTICK_RED = "#BA192F";
const VIOLET_BLUE = "#7100D9";
const WHITE = "#FFFFFF";
const BLACK = "#000000";
const PALE_GREY = "#D6D6DF";

export {
  ALMOST_BLACK,
  DARK_GREY_1,
  DARK_GREY_2,
  BLUE_GREEN,
  LIPSTICK_RED,
  VIOLET_BLUE,
  WHITE,
  BLACK,
  PALE_GREY,
}
