const ADD_LONG = 'ADD_LONG';
const ADD_SHORT = 'ADD_SHORT';
const REMOVE_LONG = 'REMOVE_LONG';
const REMOVE_SHORT = 'REMOVE_SHORT';

export {
  ADD_LONG,
  ADD_SHORT,
  REMOVE_LONG,
  REMOVE_SHORT,
}
